server:
  port: 8080
  error:
    include-message: always

spring:
  application:
    name: crediya-user-service
  devtools:
    add-properties: false
  r2dbc:
    url: r2dbc:postgresql://${SPRING_R2DBC_HOST:localhost}:5432/db_crediya_user
    username: ${SPRING_R2DBC_USERNAME:admin}
    password: ${SPRING_R2DBC_PASSWORD:admin}
  sql:
    init:
      platform: postgresql

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      probes:
        enabled: true

cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

jwt:
  secret: secretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecret
  expiration: 3600000 # 1 hour in milliseconds

db:
  host: ${SPRING_R2DBC_HOST:localhost}

